# gcloud app deploy {path to this file} --project warscry
runtime: go121

instance_class: F1
inbound_services:

env_variables:
  WARSCRY_PORT: "8080"
  WARSCRY_POLL_INTERVAL: "30"

main: ./cmd/main.go

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.9
  max_concurrent_requests: 1000
